name: Sample CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Custom Script
        run: |
          echo "Running custom script..."
          result=$((10 + 20 + 30 + 40))
          echo "The result is: $result"
